#!/bin/sh
# указываем адреса нужных списков, формируем из двух источников
/usr/bin/wget -N https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
/usr/bin/wget -N https://raw.githubusercontent.com/jfoboss/dnscrypt-domain-blacklists/master/blacklist.txt
# указываем адрес нужного белого списка
/usr/bin/wget -N https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
# извлекаем домены из списка hosts
cat hosts | grep '^0\.0\.0\.0' | awk '{print $2}' > block
# преобразуем blacklist.txt в файл mybase, удаляя лишние строки
sed '/#/d; /*/d; /^$/d; /^\./d' blacklist.txt > mybase
# сливаем три списка block, mybase и личный файл myblacklist в merged с сортировкой доменов по алфавиту
cat block mybase /etc/unbound/myblacklist | sort -u > merged
# сливаем два списка whitelist.txt и личный файл mywhitelist в whitelist с сортировкой доменов по алфавиту
cat whitelist.txt /etc/unbound/mywhitelist | sort -u > whitelist
# удаляем из merged домены белого списка whitelist
comm -23 merged whitelist > merged_corr
# удаляем старый список при обновлении
rm /etc/unbound/unbound.conf.d/hosts-alternates.conf 
# создаем список и добавляем "server:" в начало
echo "server:" > /etc/unbound/unbound.conf.d/hosts-alternates.conf
# формируем список вида local_zone: "domain" always_nxdomain
awk '{print "local-zone: \""$1"\" always_nxdomain"}' merged_corr >> /etc/unbound/unbound.conf.d/hosts-alternates.conf
# перезапускаем unbound
service unbound restart
